DEMO_COLS = ["age", "gender", "ethnicity"]


LAB_COLS = [
    "pH Other Body Fluid",
    "Lymphocytes Joint Fluid",
    "Hemoglobin Blood",
    "Basophils Joint Fluid",
    "Chloride Blood",
    "Glucose Blood",
    "Monocytes Blood",
    "Eosinophils Joint Fluid",
    "pH Urine",
    "Monocytes Ascites",
    "Basophils Cerebrospinal Fluid",
    "Hematocrit Urine",
    "Bicarbonate Blood",
    "Basophils Other Body Fluid",
    "Potassium Blood",
    "Eosinophils Blood",
    "Eosinophils Pleural",
    "L Blood",
    "Lymphocytes Ascites",
    "Creatinine Blood",
    "Eosinophils Ascites",
    "pO2 Blood",
    "Lymphocytes Other Body Fluid",
    "Hematocrit Blood",
    "Leukocytes Urine",
    "Calcium, Total Blood",
    "Anion Gap Blood",
    "Eosinophils Other Body Fluid",
    "Sodium Blood",
    "Lymphocytes Blood",
    "Basophils Pleural",
    "Lactate Blood",
    "H Blood",
    "Neutrophils Blood",
    "Monocytes Cerebrospinal Fluid",
    "Troponin T Blood",
    "Platelet Count Blood",
    "Basophils Blood",
    "Monocytes Joint Fluid",
    "Eosinophils Urine",
    "pH Blood",
    "Glucose Urine",
    "Eosinophils Cerebrospinal Fluid",
    "pCO2 Blood",
    "Basophils Ascites",
    "Lymphocytes Pleural",
]
